### ISSUE TITLE
csgo support in newest updates?

### ISSUE THREAD

**Issue by formatme** [quanticc/lawena-recording-tool#102]
could you add back csgo support?

**Comment by quanticc** [comment]
Sorry, but supporting this game is not a priority at the moment, since many of the performance and quality tweaks that work on TF2 doesn't on CSGO, providing little benefit to actually use the tool. You might achieve similar results with OBS and some in-game scripts.

**Comment by formatme** [comment]
I understand its not a priority, but i hope CSGO support still gets added, Having stuff like VDM for csgo movie making would be nice. and with obs you compress your video in the process of recording it so i rather use startmovie. It would be nice to have a workflow to have lawena and https://github.com/AronParker/AviRecorder link up and It will essentially then serve as a converter that when enabled processes all tga frames in a folder and then writes the AVI files into the AVI folder.

**Comment by joekiller** [comment]
@formatme source engine dropped Avi support for h264. #107 adds support for direct video encoding.
