### ISSUE TITLE
getdown.txt

### ISSUE THREAD

**Issue by gayfaggotbanannaman** [quanticc/lawena-recording-tool#121]
the application failed to launch due to a missing resource:
http://dl.dropboxusercontent.com/u/74380/lwrt/v4.1.x/stable/latest/getdown.txt

please visit
for information on how to handle such problems

**Comment by quanticc** [comment]
I moved away from Dropbox last year so that link has been broken since. You need to download the latest version from https://github.com/quanticc/lawena-recording-tool/releases

Duplicate of #94

**Comment by gayfaggotbanannaman** [comment]
I did download the latest version this error was found on the latest
patches installation of lawena and avoids the system from updating
