### ISSUE TITLE
Problem With Lawena Movie Folder.

### ISSUE THREAD

**Issue by Setsus** [quanticc/lawena-recording-tool#82]
Hey dude , so i installed lawena like a day ago , i just have a little problem , when i open tf2 and load my demo i press "p" and all its fine.
But when i close my demo and tf2 and i go to search my movie files , the movie folder is empty.
You can help me ?
Hope so.

-Setsus

**Comment by iabarca** [comment]
Are you sure that TF2 is recording? Game should slow down while it records, as part of the whole string of commands bound to P.

If it's recording correctly, then make sure the folder you set for recording does not have special characters, try to make it as simple as possible like "C:\Movies\". Game doesn't like certain characters in the ``startmovie`` command.

If you tried that and still doesn't work, then while the game is running with Lawena, can you please check for the following .cfg file: `<your tf folder>/cfg/mov/a1_.cfg` and let me know of its contents.

**Comment by Setsus** [comment]
Lawena record correctly , the game its slow down and when i tap "p" another time the game go faster.

When i play my tf2 this is the file that i have in my a1.cfg :startmovie "C:\Movies/a1_" tga wav

**Comment by iabarca** [comment]
Seems everything is going correctly.

I am out of ideas at the moment, maybe it's a permission issue causing TF2 not to write the frames. Lawena leverages the in-game Source Recorder `startmovie` command to record, so can you check it works for you by itself, even without Lawena?

Command works like `startmovie <folder> tga wav` to record TGA frames and a WAV file. And `endmovie` to stop.

**Comment by Setsus** [comment]
It works also without lawena , the game lagging a little bit.

The problem is that the first time i do that it works ( with lawena ) , but when i try to record the second demo it doesnt appears in my movie folder ( just the first demo ).

**Comment by Setsus** [comment]
Also dude if i want my config back how can i do ?
I mean my hitsound / crosshair etc... ( when i open tf2 without lawena , i cant use them )

Some answer for my 2 problems :( ?

**Comment by iabarca** [comment]
If the files were not restored correctly, you can get the files from the zip backup in your tf folder

**Comment by Setsus** [comment]
And for the problem with the movie folder nothing i can do ?

Il 19/Lug/2016 01:01, "Quantic" <notifications@github.com> ha scritto:

**Comment by Setsus** [comment]
And for the problem with the movie folder nothing i can do ?

**Comment by Setsus** [comment]
Also when i stop my rec. with lawena it appears this on my console :
'mov\b2' not present; not executing.
 dont know if this is a problem or not.

**Comment by Setsus** [comment]
And when i take my original custom and cfg folder in my tf and i try to record with lawena , when i finish it will appears in my movie folder.
But if i try a second time , the movie folder have only the first record.
I cant change always my custom tf2 when i want to record something.
SOme ideas ?

**Comment by iabarca** [comment]
The `'mov\b2' not present; not executing.` line is not right, that is one of the files that let's you record the second movie slot. The sequence is a1 -> b2 -> c3 -> .... etc

Normally all of those files should get copied when launching the game through Lawena. If you move around the folders while the game is on with Lawena you can break how it processes the aliases to make separate segments for each time you press P.

Make sure when you start the game with Lawena that your ``tf/cfg/mov`` folder exists and that it contains many cfg files called a1, b2, c3, etc. Also check if you have ever gotten an error message while running Lawena, like a "Failed to replace files" or similar.

**Comment by Setsus** [comment]
So , when i launch my game i have these in my mov folder : 
a1
b2
c3
d4
e5
empty
f6
etc..

And i have this in my console : 'custom.cfg' not present; not executing.
'sixense_bindings.cfg' not present; not executing.
writing bindings to c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\cfg\sixense_bindings.cfg
Hiding LobbyContainerFrameHiding LobbyContainerFrameHiding LobbyContainerFrameChanging resolutions from (1280, 720) -> (1280, 720)
Unable to remove c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\textwindow_temp.html!
[

**Comment by iabarca** [comment]
That is normal. Each time you press P to stop a recording, the program will switch to a different movie slot. You shouldn't get any errors when doing that, like the `'mov\b2' not present; not executing.` you told me earlier.

**Comment by Setsus** [comment]
This is what i get when i open tf2 with lawena but not recording anything.
Now i will post you what i get when i press "p"

**Comment by Setsus** [comment]
When i record its show me that in the console : 
'mov\a1' not present; not executing.
No movie started.

**Comment by iabarca** [comment]
Something is preventing Lawena copying its files to your TF folders. I'm not sure why yet.

**Comment by Setsus** [comment]
So dude , i do some test and it works only with 1 demo.
Just this demo , when i try to record the others it doesnt work.
I dont know why...

**Comment by joekiller** [comment]
I removed the quotes from the demo path `startmovie "d:\path/a1_" tga wav` that fixed this problem.

maybe remove the escaped quotes here https://github.com/quanticc/lawena-recording-tool/blob/98be9164e2508a02a07141c217f6975f4a2c4bb1/src/main/java/lwrt/MovieManager.java#L55

**Comment by joekiller** [comment]
Also I couldn't get it to record anywhere but in the `tf` folder.

**Comment by quanticc** [comment]
I was able to reproduce it, but this must be something relatively new because the quotes have been there since the beginning.

**Comment by quanticc** [comment]
I am not able to run tests at the moment but as soon as I figure out this console bug (can't interact with it), I'll continue investigating. Thanks for reporting it

**Comment by A-q-p-W** [comment]
i encountered this problem myself and after asking two or three people about it, they thought the problem might be caused by the forward slash in the file path used by the cfg files. So because backward slashes are usually used in file paths, TF2 might not read it properly if there is a forward slash.

Maybe this could be preventing lawena from creating the files or creating a new folder if necessary, I'm not sure. I don't have much experience with this stuff but I figured I would mention it here just in case it helps.

Example of what I'm talking about: 

C:\Movies\lawena/a1_

**Comment by truelossless** [comment]
Encountered the problem today too and it's driving me crazy. Was working fine before. After a lot of testing, i found out that absolute pathes aren't working anymore with the startmovie command. I first thought it was an permission issue but after reinstalling tf2 (yes, i was really upset), running everything as admin, i'm convinced it's something else. It may be a regression bug introduced in a recent TF2 update.

**Comment by quanticc** [comment]
I tried relative paths beneath tf folder and it works, but relative paths using ".." to go up folders doesn't. It's definitely a regression. In addition:

- Backslash or slash doesn't seem to affect the result.
- Using an absolute path, even if it's the **same** path as tf folder, doesn't work.

Thanks @truelossless for the input. I'll push a workaround to prefer relative paths in the startmovie command generator.

**Comment by truelossless** [comment]
Workaround: if this is a TF2 bug, I suggest you add a relative path support to the movie folder. (Pathes like "lawena_recordings/a1_" work as expected => tf/lawena_recordings/a1_0000.tga)

**Comment by truelossless** [comment]
Sorry, didn't see your answer. Thank you !

**Comment by quanticc** [comment]
I've discovered that if you use for example ``startmovie /a1_`` it will record to the root of the drive TF2 is located, C:\a1_0000.tga .. etc

**Comment by truelossless** [comment]
Interesting. I've already fulfilled a bug report to the TF Team but i guess that this should be added. Do you know if the command had the same behavior before or if this is a new feature ?

If Valve doesn't fix this issue, your trick will be very useful.

**Comment by truelossless** [comment]
Hi, just a quick feedback about the update you pushed 2 days ago.
If I'm not mistaken, Lawena seems to auto-detect TF2 path. However, it uses lowercase letters in the path for the hard drive (e.g "d:\program files (x86)\steam\SteamApps\common\Team Fortress 2\tf").
The problem is that your trick to record to the same hard drive doesn't work in this case.
I believe the error is from this regex:
`^[A-Z]:(.*)$`
Possible solution:
`^[A-Za-z]:(.*)$`

**Comment by quanticc** [comment]
Thanks, yeah that will certainly do it.

EDIT: This was patched in version 4.1.18-2. Automatic updater should pick it up.
